

version: '3'

services:
  briefing:
    image: holtwick/briefing
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080

# networks:
#   default:
#     external:
#       name: proxy
